# =============================================================================
# Container build
# =============================================================================

.EXPORT_ALL_VARIABLES:

LC_ALL = C # Ensure simplest POSIX locale

# Primary targets
# =============================================================================

.PHONY: build # Build the container
# -----------------------------------------------------------------------------

build:
	echo "TODO: Implement this target"
	exit 1

.PHONY: build-test # Test the build in the current container
# -----------------------------------------------------------------------------
