name: Dev Container
on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  prebuild:
    name: Prebuild image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}
          push: always
  sync-branch:
    name: Synchronize Git branch
    if: github.event_name != 'pull_request'
    needs: prebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: docker-edge
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
