name: Docker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      # https://github.com/docker/metadata-action
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          github-token: ${{ github.token }}
          tags: |
            type=schedule,pattern=nightly
            type=edge
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' }}
            type=ref,event=tag
            type=ref,event=pr
      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/build-push-action
      - uses: docker/build-push-action@v3
        with:
          context: src
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
  sync-branche:
    name: Synchronize Git branch
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: edge
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
